### PR TITLE
Commands with tables

### PR DESCRIPTION
**Pull request by Impeekay**
- Added Help command (help is a valid subcommand)
  - can be invoked by `main_class help`
  - Help to subcommands would be invoked via `main_class help subcommand` eg: `main_class help list` (gives help about list command)
- Added details subcommand
- Added table to display results on cli

### CODE REVIEW

**Comment by ZihengSun** [comment]
awesome! seems working very well! one last thing is to add some unit tests.

**Comment by ZihengSun** [comment]
Unit test should be quite straightforward by changing the `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = GeoweaverApplication.class)` to `@SpringBootTest(classes = GeoweaverCLI.class)`

**Comment by Impeekay** [comment]
Unit tests specific to command line or Basetool and others?

**Comment by ZihengSun** [comment]
> Unit tests specific to command line or Basetool and others?

Unit tests for the newly added code. Some simple tests for list and detail function.

**Review by ZihengSun — APPROVED** [review]

**Pull request merged**
